import { Color } from "three"
import useDisplayModeStore from "./useDisplayModeStore"


function hsl(h: number, s: number, l: number) {
  return new Color().setHSL(h / 360, s / 100, l / 100, 'srgb')
}

interface Colors {
  foreground: Color;
  background: Color;
  card: Color;
  cardForeground: Color;
  accent: Color;
  accentForeground: Color;
  backgroundOpacity: number;
}

// TODO:
// Copied from apfel - need adjustments
const darkColors: Colors = {
  foreground: hsl(0, 0, 100),
  background: hsl(0, 0, 0),
  card: hsl(0, 0, 53),
  cardForeground: hsl(0, 0, 100),
  accent: hsl(210, 100, 52),
  accentForeground: hsl(0, 0, 100),
  backgroundOpacity: 0.15
}

// TODO:
// generated by Copilot - need adjustments
const lightColors: Colors = {
  foreground: hsl(0, 0, 0),
  background: hsl(0, 0, 100),
  card: hsl(0, 0, 47),
  cardForeground: hsl(0, 0, 100),
  accent: hsl(210, 100, 48),
  accentForeground: hsl(0, 0, 100),
  backgroundOpacity: 0.15
}



const useColors = () => {
  const mode = useDisplayModeStore((state) => state.mode);
  return mode === 'dark' ? darkColors : lightColors;
}

export default useColors