import useDisplayModeStore from "./useDisplayModeStore"
import hsl from "../utils/hsl";

// TODO:
// Copied from apfel - need adjustments
const darkColors = {
  foreground: hsl(0, 0, 100),
  background: hsl(0, 0, 0),
  card: hsl(0, 0, 53),
  cardForeground: hsl(0, 0, 100),
  accent: hsl(210, 100, 52),
  accentForeground: hsl(0, 0, 100),
}

// TODO:
// generated by Copilot - need adjustments
const lightColors = {
  foreground: hsl(0, 0, 0),
  background: hsl(0, 0, 100),
  card: hsl(0, 0, 47),
  cardForeground: hsl(0, 0, 100),
  accent: hsl(210, 100, 48),
  accentForeground: hsl(0, 0, 100),
}



const useColors = () => {
  const mode = useDisplayModeStore((state) => state.mode);
  return mode === 'dark' ? darkColors : lightColors;
}

export default useColors