import { Container, Image, Text } from "@react-three/uikit"
import GuideStrip from "./GuideStrip";
import useColors from "../../hooks/useColors";
import { GuideStripProgramProps } from "./GuideStripProgram";

export interface ScheduleEntry {
    title: string;
    startTime: string;
    endTime: string;
}
export interface ProgramSchedule {
    imageUrl: string;
    /**
     * Fallback text to display if there is no image
     */
    fallbackText?: string;
    schedule: ScheduleEntry[];
}

export interface GuideProps {
    schedule: ProgramSchedule[];
    /**
     * Can override the start time of the schedule
     * Must be in the format "HH:MM"
     */
    overrideStartTime?: string;
    /**
     * Zoom level of the guide
     * Default is 1
     */
    zoomLevel: number;
}

const Guide = ({ schedule, overrideStartTime, zoomLevel = 1 }: GuideProps) => {
    const colors = useColors();

    // 120 pixel = 30 minutes
    // => 1 pixel = 0.25 minutes
    // => 1 minute = 4 pixels
    const timeTitles = () => {
        const startTime = getStartTime(schedule);

        /**
         * Get the end time by going through the entire schedule
         * for every channel and every program
         * and finding the latest end time
         */
        let endTime = startTime;
        for (const channel in schedule) {
            for (const program in schedule[channel].schedule) {
                if (schedule[channel].schedule[program].endTime > endTime) {
                    endTime = schedule[channel].schedule[program].endTime;
                }
            }
        }
        return generateTimeTexts(startTime, endTime);
    }

    const getStartTime = (schedule: ProgramSchedule[]): string => {
        if (overrideStartTime) {
            return overrideStartTime;
        }
        let startTime: string | null = null;

        schedule.forEach((channel) => {
            channel.schedule.forEach((program) => {
                if (startTime === null || program.startTime < startTime) {
                    startTime = program.startTime;
                }
            });
        });

        if (startTime === null) {
            startTime = "00:00";
        }
        return startTime;
    }

    // Generated by ChatGPT
    const getTimeInMinutes = (time: string): number => {
        const [hours, minutes] = time.split(':').map(Number);
        return hours * 60 + minutes;
    };

    const getTimeDifferenceInMinutes = (startTime: string, endTime: string): number => {
        const startMinutes = getTimeInMinutes(startTime);
        const endMinutes = getTimeInMinutes(endTime);
        return endMinutes - startMinutes;
    };

    // Generated by ChatGPT
    const formatTime = (minutes: number): string => {
        const hours = Math.floor(minutes / 60);
        const mins = minutes % 60;
        return `${String(hours).padStart(2, '0')}:${String(mins).padStart(2, '0')}`;
    };

    // Generated by ChatGPT
    const generateTimeTexts = (startTime: string, endTime: string): string[] => {
        let startMinutes = getTimeInMinutes(startTime);
        const endMinutes = getTimeInMinutes(endTime);

        // Find the next half hour after the start time
        startMinutes = Math.ceil(startMinutes / 30) * 30;

        // Find the last half hour before the end time
        const adjustedEndMinutes = Math.floor(endMinutes / 30) * 30;

        const timeTexts: string[] = [];
        for (let time = startMinutes; time < adjustedEndMinutes; time += 30) {
            timeTexts.push(formatTime(time));
        }

        return timeTexts;
    };

    const GeneratedChannelStrip = ({ programSchedule }: { programSchedule: ProgramSchedule }) => {
        const programs: (GuideStripProgramProps & { key: number })[] = [];
        const guideStartTime = getStartTime(schedule);
        let lastEndTime: string = guideStartTime;

        programSchedule.schedule.forEach((scheduleEntry, index) => {
            
            //console.log(guideStartTime);
            //scheduleEntry.endTime < guideStartTime ? console.log("End time smaller") : console.log("End time larger")            // Discard everything before the guide start time
            if (scheduleEntry.endTime < guideStartTime) return;
            //console.log("Still executed")

            const startTime = scheduleEntry.startTime;
            const endTime = scheduleEntry.endTime;
            const programWidth = getTimeDifferenceInMinutes(startTime, endTime) * 4 * zoomLevel;
            const program = {
                text: scheduleEntry.title,
                width: programWidth,
                key: index,
                gapBefore: 0
            };

            // Check if there's a previous program and if there's a gap
            if (lastEndTime && startTime > lastEndTime) {
                const gapBefore = getTimeDifferenceInMinutes(lastEndTime, startTime) * 4 * zoomLevel;
                program.gapBefore = gapBefore; // Set the gapBefore property
            } else if (index === 0 && startTime > guideStartTime) {
                const gapBefore = getTimeDifferenceInMinutes(guideStartTime, startTime) * 4 * zoomLevel;
                program.gapBefore = gapBefore; // Set the gapBefore property
            } else if (startTime < guideStartTime) {
                program.width -= getTimeDifferenceInMinutes(startTime, guideStartTime) * 4 * zoomLevel;
            }
            programs.push(program);
            lastEndTime = endTime; // Update the lastEndTime to the current program's endTime
        });
        return (
            <>
                <GuideStrip programs={programs} />
            </>
        )
    }

    return (
        <Container display={"flex"} flexDirection={"row"} gap={20} overflow={"scroll"} >
            {/** Channels displayed by their logo */}
            <Container display={"flex"} flexDirection={"column"} alignItems={"center"} gap={10} flexGrow={0} flexShrink={0}>
                {/** Empty top row to match the time header of the actual schedule */}
                <Container display={"flex"} flexDirection={"row"} gap={10} height={20}>
                </Container>
                {schedule.map((scheduleEntry, index) => (
                    <Container key={index} height={65} display={"flex"} flexDirection={"column"} justifyContent={"center"}>
                        {scheduleEntry.imageUrl ?
                            <Image width={100} src={scheduleEntry.imageUrl} flexGrow={0} flexShrink={0} />
                            : <Text width={100} color={colors.primary} textAlign={"center"}>{scheduleEntry.fallbackText || "No name available"}</Text>}
                    </Container>
                ))}
            </Container>
            {/** Actual schedule display including the time titles */}
            <Container display={"flex"} flexDirection={"column"} alignItems={"flex-start"} justifyContent={"flex-start"} gap={10} flexGrow={0} flexShrink={0}>
                {/** Time display */}
                <Container height={20}>
                    {timeTitles().map((time, index) => (
                        <Text key={index} color={colors.primary} positionType={"absolute"} positionLeft={index * 120 * zoomLevel + getTimeDifferenceInMinutes(getStartTime(schedule), timeTitles()[0] || getStartTime(schedule)) * 4} textAlign={"center"} transformTranslateX={"-50%"}>{time}</Text>
                    ))}
                </Container>
                <Container overflow={"visible"} flexDirection={"column"} gap={10}>
                    {schedule.map((scheduleEntry, index) => (
                        <GeneratedChannelStrip programSchedule={scheduleEntry} key={index} />
                    ))}
                </Container>
            </Container>
        </Container>
    )
}

export default Guide;