name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x] # Could add more node versions like so: [20.x, 22.x], but I think just 1 is enough

    steps:
      - uses: actions/checkout@v4
      - name: "Use Node.js to execute CI"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install dependencies and build app"
        working-directory: "./app"
        run: |
          echo $(pwd)
          echo $(ls -1)
          npm ci
          npm run typecheck
          npm run lint -- --quiet
          npm run build
